### PR TITLE
Misc MongoDB Connector Fixes 

### LINKED ISSUE #5613: Can't figure out how to do a delete request using the mongoDB connector
I'm using your hosted version, I've succesfully connected to mongoDB and can display everything that I need. The problem is that I can't delete something

These are the querries I've tried
{ "_id" : "{{id}}" } this one seems to work but return a delte count of 0, and the Id I'm using is 100% in the default input the same.
{ "_id" : ObjectId("{{id}}") } this one returns a mistake

**Screenshots**
image
image
image
image

### PR DESCRIPTION
**Pull request by mike12345567**
## Description
Rebase of #5875 for @melohagan 

Added support for ObjectIds. Made some fixes for the CRUD operations.

Addresses: 
- ObjectId bug: https://github.com/Budibase/budibase/issues/5613
- General Query issues: https://github.com/Budibase/budibase/issues/5387

There's still a number of improvements to be done in the V2 connector, but this should help a bit in the meantime.

## Screenshots
**Insert**
mongodb_insert

**Update**
mongodb_update

### CODE REVIEW

File: packages/server/src/integrations/mongodb.ts [hunk 1]
```diff
@@ -6,13 +7,19 @@ import {
...
 
   interface MongoDBConfig {
     connectionString: string
     db: string
   }
 
+  interface UpdateDoc {
+    filter: object
+    update: object
+    options: Object
```
Comment (Rory-Powell) [inline packages/server/src/integrations/mongodb.ts:20]: If the `Object` vs `object` usage above isn't intentional we could make the options an `object` as well. I have always used the upper case variant without much thought, after seeing this I had a look at this great article:
https://2ality.com/2020/01/typing-objects-typescript.html#object-vs.-object-in-typescript

The tldr is `Object` allows for primitives, which we would use defined types for anyway like `string` `number` so we can just use `object`  here and probably in most cases.

File: packages/server/src/integrations/mongodb.ts [hunk 2]
```diff
@@ -141,18 +183,27 @@ module MongoDBModule {
       }
     }
 
-    async update(query: { json: object; extra: { [key: string]: string } }) {
+    async update(query: { json: UpdateDoc; extra: { [key: string]: string } }) {
```
Comment (Rory-Powell) [inline packages/server/src/integrations/mongodb.ts:186]: Instead of defining our own type here for `UpdateDoc` we can use the official mongo types. To do this there would only be a few changes needed

1. Add the dependency
```
yarn add --dev @types/mongodb@3.6.3
```

2. Update the mongo import, instead of `require` use `import`. Move this to the top level of the file outside of `MongoDBModule`
```
import { MongoClient, ObjectId } from "mongodb"
```

I tried this locally and there are a few req squiggly lines around our usage of the mongo client, similar to using the `UpdateDoc` fix, maybe there could be more

File: packages/server/src/integrations/mongodb.ts (hunk 1 above)
Comment (melohagan) [reply packages/server/src/integrations/mongodb.ts]: Good catch! I'd also accidentally brought in an Object class from an aws library, so I removed that import as well.

File: packages/server/src/integrations/mongodb.ts (hunk 2 above)
Comment (melohagan) [reply packages/server/src/integrations/mongodb.ts]: I brought in the official types. 

Doing this made me realised I'm probably doing this wrong, but it might be okay for now? 

To do filter/updates with this implementation you need to do:
```
{
  "filter": { "name": "A" },
  "update": { "$set": { "name": "B" } }
}  
```
but if you were doing this as a mongodb query it should really be:
**Update One Selected**
```
{ "name": "A" },
{ "$set": { "name": "B" } }
```

Comment (Rory-Powell) [reply packages/server/src/integrations/mongodb.ts]: I see what you mean, having the two different dialects isn't ideal here, this will add translation from the bb query domain to the mongo one that'll need extra docs, etc. Probably the right way here is to have fields rendered based on the query type selected, that sounds like a v2 thing though. 

The simplest thing to do for now might be to allow them to paste an identical mongo query and try to determine which part is the operator object in the update queries `findOneAndUpdate`, `updateOne` and `updateMany`. Could be a simple check for `$` in the key, and fallback to the second object which seems to be the case in all the example docs.

**Review by shogunpurple — APPROVED** [review]
Nice! This is actually a very significant enhancement and turns on a lot of Mongos features in this connector.

File: packages/server/src/integrations/mongodb.ts (hunk 2 above)
Comment (melohagan) [reply packages/server/src/integrations/mongodb.ts]: I've updated it to parse the params if needed. So both of the options above will now work.

Comment (Rory-Powell) [reply packages/server/src/integrations/mongodb.ts]: sounds great, good job mel 👍
