### PR TITLE
Checklist API performance on default tenants and email invitations

### LINKED ISSUE #4522: Error inviting user but the user is emailed with an invite anyway
**Describe the bug**
When inviting a user to Budibase you sometimes get a "Error inviting user" error message. But the user gets the invitation email but cannot sign up.

**To Reproduce**
1. Setup SMTP
2. Go to Users
3. Click on Add user
4. Fill out their email address
5. Click Add user
6. "Error inviting user" appears

**Expected behavior**
The user does not receive the email if there is an error.

**Additional context**
If you create the user through basic on boarding, the user can reset their password and then gain access.

### PR DESCRIPTION
**Pull request by mike12345567**
## Description
There was an issue with the checklist call taking upwards of two seconds to respond. This is a relatively simple call, it shouldn't have any heavy database calls.

This also fixes #4522 - there was some issues introduced by the frontend-core that needed fixed for this flow to work correctly.

Can see the call here:
image

It appeared to be tied to the default tenant, as there was an edge case which meant that the default tenant couldn't use the more efficient app tenant lookup, instead it has to lookup the full list of app IDs. I added an efficient flag to the `getAllApps` function so that we can state that we want it to be as fast as possible, perhaps sacrificing some accuracy in the default tenant. This is fine for the checklist call because it only needs a list of apps in the tenant. This should speed up the login process for the default tenant fairly significantly.

### CODE REVIEW

**Review by shogunpurple — APPROVED** [review]
Nice one! Good catch

File: packages/builder/src/stores/portal/users.js [hunk 1]
```diff
@@ -11,15 +11,15 @@ export function createUsersStore() {
   }
 
   async function invite({ email, builder, admin }) {
-    await API.inviteUser({
+    return API.inviteUser({
```
Comment (aptkingston) [inline packages/builder/src/stores/portal/users.js:14]: Should be `return await` shouldn't it?

File: packages/builder/src/stores/portal/users.js [hunk 2]
```diff
@@ -11,15 +11,15 @@ export function createUsersStore() {
...
       email,
       builder,
       admin,
     })
   }
 
   async function acceptInvite(inviteCode, password) {
-    await API.acceptInvite({
+    return API.acceptInvite({
```
Comment (aptkingston) [inline packages/builder/src/stores/portal/users.js:22]: Should be `return await` shouldn't it?

**Review by aptkingston — COMMENTED** [review]
Knew there would be at least one issue with all the renaming in frontend core! I'm glad it's taken us this long to find one though haha.

File: packages/builder/src/stores/portal/users.js (hunk 2 above)
Comment (mike12345567) [reply packages/builder/src/stores/portal/users.js:22]: Same as above.
