### PR TITLE
Merge both create user modals for easy switch between the two

### LINKED ISSUE #4636: It is not possible to switch back from basic onboarding to email onboarding
**Describe the bug**
When onboarding a new user, you have two options: email or basic onboarding. Using the dropdown you can select which method you want to use. When selecting basic onboarding, it is not possible to switch back to email onboarding, other than closing the dialog and clicking the 'Add user' button again.

**To Reproduce**
1. Go to the dashboard
2. Click on Users
3. Click on the 'Add user' to start onboarding a new user
4. Select 'basic onboarding' from the dropdown. 
5. There is no way to switch back to email onboarding

**Expected behavior**
Keep the dropdown always visible, to give the user a possibility to change the onboarding method without closing the dialog.

**Note:** The label `username` in the basic onboarding modal is incorrect, because when you start typing a username, it throws an error: "Please enter a valid email". So the label should say `email` instead of `username`. 

**Screenshots**
**Email onboarding**
image

**Basic onboarding**
image

**Desktop (please complete the following information):**
 - OS: PopOS 21.10
 - Browser: Vivaldi
 - Version: develop branch

### PR DESCRIPTION
**Pull request by mslourens**
## Description
In order to switch easily between email based onboarding and basic onboarding, both modals needed to be merged and the content switched depending on the selected option. 

Fixes #4636

### CODE REVIEW

File: packages/builder/src/pages/builder/portal/manage/users/_components/AddUserModal.svelte [hunk 1]
```diff
@@ -49,17 +74,27 @@
...
+    <Input disabled label="Password" value={password} />
+  {:else}
+    <Input
+      type="email"
+      bind:value={$email}
+      error={$touched && $error}
+      placeholder="john@doe.com"
+      label="Email"
+    />
+  {/if}
```
Comment (aptkingston) [inline packages/builder/src/pages/builder/portal/manage/users/_components/AddUserModal.svelte:97]: The email inputs are identical here aren't they? So we could just define one of them, and move the `{#if basic}` to after that, and then just render the password input if they want basic onboading? Just to reduce duplication.

**Review by aptkingston — APPROVED** [review]
LGTM @mslourens! Much cleaner - thanks again.

Just suggested one small refactor.

**Review by aptkingston — APPROVED** [review]
LGTM!

**Comment by aptkingston** [comment]
Hey @mslourens. If you get a minute, would you be able to pull develop into this PR again? As for the conflict, you can just ignore the change to `BasicOnboadingModal` and delete it again.

If you don't have time, just let me know and I'll create a patch from your changes and open a new PR again and solve the conflict, and credit you like I did with the other one.

Thanks!

**Comment by aptkingston** [comment]
Thanks for pulling in `develop`! There's still the conflict preventing the merge (and I can't delete a file from the Github web editor), so could you quickly run a `git rm packages/builder/src/pages/builder/portal/manage/users/_components/BasicOnboardingModal.svelte` and commit that to solve the conflict and we'll get this merged? Thanks!

**Comment by aptkingston** [comment]
Thanks @mslourens!
